global:
    memo: ForrestWind
default_chain: GAIA
chains:
  GAIA:
    key: gaia-icq
    chain-id: GAIA
    rpc-addr: http://127.0.0.1:44657
    grpc-addr: http://127.0.0.1:44090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  STRIDE-TESTNET-4:
    key: stride-icq
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://127.0.0.1:33657
    grpc-addr: http://127.0.0.1:9790
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
